package com.pwz.gupiao.pojo;

import com.pwz.back.po.BaseEntity;

import java.io.Serializable;
import java.lang.reflect.Field;
import java.util.Date;

public class GuPiao extends BaseEntity implements Serializable {
    public static void main(String[] args) {

        Field[] fields = GuPiao.class.getDeclaredFields();
        for (Field field : fields) {
            String fi = field.getName();
            String d = "    <if test=\""+fi+" != null and "+fi+" != '' \">\n" +
                    "      and\ta."+fi+" = #{"+fi+"}\n" +
                    "    </if>";
            System.out.println(d);
        }


    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gu_piao.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gu_piao.ming_zi
     *
     * @mbggenerated
     */
    private String mingZi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gu_piao.dai_ma
     *
     * @mbggenerated
     */
    private String daiMa;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gu_piao.dang_qian_jia_ge
     *
     * @mbggenerated
     */
    private Double dangQianJiaGe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gu_piao.zuo_shou
     *
     * @mbggenerated
     */
    private Double zuoShou;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gu_piao.jin_kai
     *
     * @mbggenerated
     */
    private Double jinKai;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gu_piao.cheng_jiao_liang__shou
     *
     * @mbggenerated
     */
    private Double chengJiaoLiangShou;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gu_piao.wai_pan
     *
     * @mbggenerated
     */
    private Double waiPan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gu_piao.nei_pan
     *
     * @mbggenerated
     */
    private Double neiPan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gu_piao.mai_yi
     *
     * @mbggenerated
     */
    private Double maiYi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gu_piao.mai_yi_liang__shou2
     *
     * @mbggenerated
     */
    private Double maiYiLiangShou2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gu_piao.mai_2
     *
     * @mbggenerated
     */
    private Double mai2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gu_piao.mai_3
     *
     * @mbggenerated
     */
    private Double mai3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gu_piao.mai_4
     *
     * @mbggenerated
     */
    private Double mai4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gu_piao.mai_5
     *
     * @mbggenerated
     */
    private Double mai5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gu_piao.ma_yi
     *
     * @mbggenerated
     */
    private Double maYi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gu_piao.ma_yi_liang
     *
     * @mbggenerated
     */
    private Double maYiLiang;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gu_piao.ma_2
     *
     * @mbggenerated
     */
    private Double ma2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gu_piao.ma_3
     *
     * @mbggenerated
     */
    private Double ma3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gu_piao.ma_4
     *
     * @mbggenerated
     */
    private Double ma4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gu_piao.ma_5
     *
     * @mbggenerated
     */
    private Double ma5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gu_piao.zui_jin_zhu_bi_cheng_jiao
     *
     * @mbggenerated
     */
    private Double zuiJinZhuBiChengJiao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gu_piao.shi_jian
     *
     * @mbggenerated
     */
    private Double shiJian;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gu_piao.zhang_die
     *
     * @mbggenerated
     */
    private Double zhangDie;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gu_piao.zhang_die2
     *
     * @mbggenerated
     */
    private Double zhangDie2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gu_piao.zui_gao
     *
     * @mbggenerated
     */
    private Double zuiGao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gu_piao.zui_di
     *
     * @mbggenerated
     */
    private Double zuiDi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gu_piao.jia_ge
     *
     * @mbggenerated
     */
    private Double jiaGe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gu_piao.cheng_jiao_liang
     *
     * @mbggenerated
     */
    private Double chengJiaoLiang;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gu_piao.cheng_jiao_e
     *
     * @mbggenerated
     */
    private Double chengJiaoE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gu_piao.cheng_jiao_liang__shou2
     *
     * @mbggenerated
     */
    private Double chengJiaoLiangShou2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gu_piao.cheng_jiao_e__wan2
     *
     * @mbggenerated
     */
    private Double chengJiaoEWan2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gu_piao.huan_shou_lu
     *
     * @mbggenerated
     */
    private Double huanShouLu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gu_piao.shi_ying_lu
     *
     * @mbggenerated
     */
    private Double shiYingLu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gu_piao.zui_gao2
     *
     * @mbggenerated
     */
    private Double zuiGao2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gu_piao.zui_di2
     *
     * @mbggenerated
     */
    private Double zuiDi2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gu_piao.zhen_fu
     *
     * @mbggenerated
     */
    private Double zhenFu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gu_piao.liu_tong_shi_zhi
     *
     * @mbggenerated
     */
    private Double liuTongShiZhi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gu_piao.zong_shi_zhi
     *
     * @mbggenerated
     */
    private Double zongShiZhi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gu_piao.shi_jing_lu
     *
     * @mbggenerated
     */
    private Double shiJingLu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gu_piao.zhang_ting_jia
     *
     * @mbggenerated
     */
    private Double zhangTingJia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gu_piao.die_ting_jia
     *
     * @mbggenerated
     */
    private Double dieTingJia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gu_piao.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gu_piao.create_guid
     *
     * @mbggenerated
     */
    private String createGuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gu_piao.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gu_piao.modify_guid
     *
     * @mbggenerated
     */
    private String modifyGuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gu_piao.is_deleted
     *
     * @mbggenerated
     */
    private Boolean isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gu_piao
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gu_piao.id
     *
     * @return the value of gu_piao.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gu_piao.id
     *
     * @param id the value for gu_piao.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gu_piao.ming_zi
     *
     * @return the value of gu_piao.ming_zi
     *
     * @mbggenerated
     */
    public String getMingZi() {
        return mingZi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gu_piao.ming_zi
     *
     * @param mingZi the value for gu_piao.ming_zi
     *
     * @mbggenerated
     */
    public void setMingZi(String mingZi) {
        this.mingZi = mingZi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gu_piao.dai_ma
     *
     * @return the value of gu_piao.dai_ma
     *
     * @mbggenerated
     */
    public String getDaiMa() {
        return daiMa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gu_piao.dai_ma
     *
     * @param daiMa the value for gu_piao.dai_ma
     *
     * @mbggenerated
     */
    public void setDaiMa(String daiMa) {
        this.daiMa = daiMa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gu_piao.dang_qian_jia_ge
     *
     * @return the value of gu_piao.dang_qian_jia_ge
     *
     * @mbggenerated
     */
    public Double getDangQianJiaGe() {
        return dangQianJiaGe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gu_piao.dang_qian_jia_ge
     *
     * @param dangQianJiaGe the value for gu_piao.dang_qian_jia_ge
     *
     * @mbggenerated
     */
    public void setDangQianJiaGe(Double dangQianJiaGe) {
        this.dangQianJiaGe = dangQianJiaGe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gu_piao.zuo_shou
     *
     * @return the value of gu_piao.zuo_shou
     *
     * @mbggenerated
     */
    public Double getZuoShou() {
        return zuoShou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gu_piao.zuo_shou
     *
     * @param zuoShou the value for gu_piao.zuo_shou
     *
     * @mbggenerated
     */
    public void setZuoShou(Double zuoShou) {
        this.zuoShou = zuoShou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gu_piao.jin_kai
     *
     * @return the value of gu_piao.jin_kai
     *
     * @mbggenerated
     */
    public Double getJinKai() {
        return jinKai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gu_piao.jin_kai
     *
     * @param jinKai the value for gu_piao.jin_kai
     *
     * @mbggenerated
     */
    public void setJinKai(Double jinKai) {
        this.jinKai = jinKai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gu_piao.cheng_jiao_liang__shou
     *
     * @return the value of gu_piao.cheng_jiao_liang__shou
     *
     * @mbggenerated
     */
    public Double getChengJiaoLiangShou() {
        return chengJiaoLiangShou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gu_piao.cheng_jiao_liang__shou
     *
     * @param chengJiaoLiangShou the value for gu_piao.cheng_jiao_liang__shou
     *
     * @mbggenerated
     */
    public void setChengJiaoLiangShou(Double chengJiaoLiangShou) {
        this.chengJiaoLiangShou = chengJiaoLiangShou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gu_piao.wai_pan
     *
     * @return the value of gu_piao.wai_pan
     *
     * @mbggenerated
     */
    public Double getWaiPan() {
        return waiPan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gu_piao.wai_pan
     *
     * @param waiPan the value for gu_piao.wai_pan
     *
     * @mbggenerated
     */
    public void setWaiPan(Double waiPan) {
        this.waiPan = waiPan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gu_piao.nei_pan
     *
     * @return the value of gu_piao.nei_pan
     *
     * @mbggenerated
     */
    public Double getNeiPan() {
        return neiPan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gu_piao.nei_pan
     *
     * @param neiPan the value for gu_piao.nei_pan
     *
     * @mbggenerated
     */
    public void setNeiPan(Double neiPan) {
        this.neiPan = neiPan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gu_piao.mai_yi
     *
     * @return the value of gu_piao.mai_yi
     *
     * @mbggenerated
     */
    public Double getMaiYi() {
        return maiYi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gu_piao.mai_yi
     *
     * @param maiYi the value for gu_piao.mai_yi
     *
     * @mbggenerated
     */
    public void setMaiYi(Double maiYi) {
        this.maiYi = maiYi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gu_piao.mai_yi_liang__shou2
     *
     * @return the value of gu_piao.mai_yi_liang__shou2
     *
     * @mbggenerated
     */
    public Double getMaiYiLiangShou2() {
        return maiYiLiangShou2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gu_piao.mai_yi_liang__shou2
     *
     * @param maiYiLiangShou2 the value for gu_piao.mai_yi_liang__shou2
     *
     * @mbggenerated
     */
    public void setMaiYiLiangShou2(Double maiYiLiangShou2) {
        this.maiYiLiangShou2 = maiYiLiangShou2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gu_piao.mai_2
     *
     * @return the value of gu_piao.mai_2
     *
     * @mbggenerated
     */
    public Double getMai2() {
        return mai2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gu_piao.mai_2
     *
     * @param mai2 the value for gu_piao.mai_2
     *
     * @mbggenerated
     */
    public void setMai2(Double mai2) {
        this.mai2 = mai2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gu_piao.mai_3
     *
     * @return the value of gu_piao.mai_3
     *
     * @mbggenerated
     */
    public Double getMai3() {
        return mai3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gu_piao.mai_3
     *
     * @param mai3 the value for gu_piao.mai_3
     *
     * @mbggenerated
     */
    public void setMai3(Double mai3) {
        this.mai3 = mai3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gu_piao.mai_4
     *
     * @return the value of gu_piao.mai_4
     *
     * @mbggenerated
     */
    public Double getMai4() {
        return mai4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gu_piao.mai_4
     *
     * @param mai4 the value for gu_piao.mai_4
     *
     * @mbggenerated
     */
    public void setMai4(Double mai4) {
        this.mai4 = mai4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gu_piao.mai_5
     *
     * @return the value of gu_piao.mai_5
     *
     * @mbggenerated
     */
    public Double getMai5() {
        return mai5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gu_piao.mai_5
     *
     * @param mai5 the value for gu_piao.mai_5
     *
     * @mbggenerated
     */
    public void setMai5(Double mai5) {
        this.mai5 = mai5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gu_piao.ma_yi
     *
     * @return the value of gu_piao.ma_yi
     *
     * @mbggenerated
     */
    public Double getMaYi() {
        return maYi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gu_piao.ma_yi
     *
     * @param maYi the value for gu_piao.ma_yi
     *
     * @mbggenerated
     */
    public void setMaYi(Double maYi) {
        this.maYi = maYi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gu_piao.ma_yi_liang
     *
     * @return the value of gu_piao.ma_yi_liang
     *
     * @mbggenerated
     */
    public Double getMaYiLiang() {
        return maYiLiang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gu_piao.ma_yi_liang
     *
     * @param maYiLiang the value for gu_piao.ma_yi_liang
     *
     * @mbggenerated
     */
    public void setMaYiLiang(Double maYiLiang) {
        this.maYiLiang = maYiLiang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gu_piao.ma_2
     *
     * @return the value of gu_piao.ma_2
     *
     * @mbggenerated
     */
    public Double getMa2() {
        return ma2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gu_piao.ma_2
     *
     * @param ma2 the value for gu_piao.ma_2
     *
     * @mbggenerated
     */
    public void setMa2(Double ma2) {
        this.ma2 = ma2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gu_piao.ma_3
     *
     * @return the value of gu_piao.ma_3
     *
     * @mbggenerated
     */
    public Double getMa3() {
        return ma3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gu_piao.ma_3
     *
     * @param ma3 the value for gu_piao.ma_3
     *
     * @mbggenerated
     */
    public void setMa3(Double ma3) {
        this.ma3 = ma3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gu_piao.ma_4
     *
     * @return the value of gu_piao.ma_4
     *
     * @mbggenerated
     */
    public Double getMa4() {
        return ma4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gu_piao.ma_4
     *
     * @param ma4 the value for gu_piao.ma_4
     *
     * @mbggenerated
     */
    public void setMa4(Double ma4) {
        this.ma4 = ma4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gu_piao.ma_5
     *
     * @return the value of gu_piao.ma_5
     *
     * @mbggenerated
     */
    public Double getMa5() {
        return ma5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gu_piao.ma_5
     *
     * @param ma5 the value for gu_piao.ma_5
     *
     * @mbggenerated
     */
    public void setMa5(Double ma5) {
        this.ma5 = ma5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gu_piao.zui_jin_zhu_bi_cheng_jiao
     *
     * @return the value of gu_piao.zui_jin_zhu_bi_cheng_jiao
     *
     * @mbggenerated
     */
    public Double getZuiJinZhuBiChengJiao() {
        return zuiJinZhuBiChengJiao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gu_piao.zui_jin_zhu_bi_cheng_jiao
     *
     * @param zuiJinZhuBiChengJiao the value for gu_piao.zui_jin_zhu_bi_cheng_jiao
     *
     * @mbggenerated
     */
    public void setZuiJinZhuBiChengJiao(Double zuiJinZhuBiChengJiao) {
        this.zuiJinZhuBiChengJiao = zuiJinZhuBiChengJiao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gu_piao.shi_jian
     *
     * @return the value of gu_piao.shi_jian
     *
     * @mbggenerated
     */
    public Double getShiJian() {
        return shiJian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gu_piao.shi_jian
     *
     * @param shiJian the value for gu_piao.shi_jian
     *
     * @mbggenerated
     */
    public void setShiJian(Double shiJian) {
        this.shiJian = shiJian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gu_piao.zhang_die
     *
     * @return the value of gu_piao.zhang_die
     *
     * @mbggenerated
     */
    public Double getZhangDie() {
        return zhangDie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gu_piao.zhang_die
     *
     * @param zhangDie the value for gu_piao.zhang_die
     *
     * @mbggenerated
     */
    public void setZhangDie(Double zhangDie) {
        this.zhangDie = zhangDie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gu_piao.zhang_die2
     *
     * @return the value of gu_piao.zhang_die2
     *
     * @mbggenerated
     */
    public Double getZhangDie2() {
        return zhangDie2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gu_piao.zhang_die2
     *
     * @param zhangDie2 the value for gu_piao.zhang_die2
     *
     * @mbggenerated
     */
    public void setZhangDie2(Double zhangDie2) {
        this.zhangDie2 = zhangDie2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gu_piao.zui_gao
     *
     * @return the value of gu_piao.zui_gao
     *
     * @mbggenerated
     */
    public Double getZuiGao() {
        return zuiGao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gu_piao.zui_gao
     *
     * @param zuiGao the value for gu_piao.zui_gao
     *
     * @mbggenerated
     */
    public void setZuiGao(Double zuiGao) {
        this.zuiGao = zuiGao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gu_piao.zui_di
     *
     * @return the value of gu_piao.zui_di
     *
     * @mbggenerated
     */
    public Double getZuiDi() {
        return zuiDi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gu_piao.zui_di
     *
     * @param zuiDi the value for gu_piao.zui_di
     *
     * @mbggenerated
     */
    public void setZuiDi(Double zuiDi) {
        this.zuiDi = zuiDi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gu_piao.jia_ge
     *
     * @return the value of gu_piao.jia_ge
     *
     * @mbggenerated
     */
    public Double getJiaGe() {
        return jiaGe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gu_piao.jia_ge
     *
     * @param jiaGe the value for gu_piao.jia_ge
     *
     * @mbggenerated
     */
    public void setJiaGe(Double jiaGe) {
        this.jiaGe = jiaGe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gu_piao.cheng_jiao_liang
     *
     * @return the value of gu_piao.cheng_jiao_liang
     *
     * @mbggenerated
     */
    public Double getChengJiaoLiang() {
        return chengJiaoLiang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gu_piao.cheng_jiao_liang
     *
     * @param chengJiaoLiang the value for gu_piao.cheng_jiao_liang
     *
     * @mbggenerated
     */
    public void setChengJiaoLiang(Double chengJiaoLiang) {
        this.chengJiaoLiang = chengJiaoLiang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gu_piao.cheng_jiao_e
     *
     * @return the value of gu_piao.cheng_jiao_e
     *
     * @mbggenerated
     */
    public Double getChengJiaoE() {
        return chengJiaoE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gu_piao.cheng_jiao_e
     *
     * @param chengJiaoE the value for gu_piao.cheng_jiao_e
     *
     * @mbggenerated
     */
    public void setChengJiaoE(Double chengJiaoE) {
        this.chengJiaoE = chengJiaoE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gu_piao.cheng_jiao_liang__shou2
     *
     * @return the value of gu_piao.cheng_jiao_liang__shou2
     *
     * @mbggenerated
     */
    public Double getChengJiaoLiangShou2() {
        return chengJiaoLiangShou2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gu_piao.cheng_jiao_liang__shou2
     *
     * @param chengJiaoLiangShou2 the value for gu_piao.cheng_jiao_liang__shou2
     *
     * @mbggenerated
     */
    public void setChengJiaoLiangShou2(Double chengJiaoLiangShou2) {
        this.chengJiaoLiangShou2 = chengJiaoLiangShou2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gu_piao.cheng_jiao_e__wan2
     *
     * @return the value of gu_piao.cheng_jiao_e__wan2
     *
     * @mbggenerated
     */
    public Double getChengJiaoEWan2() {
        return chengJiaoEWan2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gu_piao.cheng_jiao_e__wan2
     *
     * @param chengJiaoEWan2 the value for gu_piao.cheng_jiao_e__wan2
     *
     * @mbggenerated
     */
    public void setChengJiaoEWan2(Double chengJiaoEWan2) {
        this.chengJiaoEWan2 = chengJiaoEWan2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gu_piao.huan_shou_lu
     *
     * @return the value of gu_piao.huan_shou_lu
     *
     * @mbggenerated
     */
    public Double getHuanShouLu() {
        return huanShouLu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gu_piao.huan_shou_lu
     *
     * @param huanShouLu the value for gu_piao.huan_shou_lu
     *
     * @mbggenerated
     */
    public void setHuanShouLu(Double huanShouLu) {
        this.huanShouLu = huanShouLu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gu_piao.shi_ying_lu
     *
     * @return the value of gu_piao.shi_ying_lu
     *
     * @mbggenerated
     */
    public Double getShiYingLu() {
        return shiYingLu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gu_piao.shi_ying_lu
     *
     * @param shiYingLu the value for gu_piao.shi_ying_lu
     *
     * @mbggenerated
     */
    public void setShiYingLu(Double shiYingLu) {
        this.shiYingLu = shiYingLu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gu_piao.zui_gao2
     *
     * @return the value of gu_piao.zui_gao2
     *
     * @mbggenerated
     */
    public Double getZuiGao2() {
        return zuiGao2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gu_piao.zui_gao2
     *
     * @param zuiGao2 the value for gu_piao.zui_gao2
     *
     * @mbggenerated
     */
    public void setZuiGao2(Double zuiGao2) {
        this.zuiGao2 = zuiGao2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gu_piao.zui_di2
     *
     * @return the value of gu_piao.zui_di2
     *
     * @mbggenerated
     */
    public Double getZuiDi2() {
        return zuiDi2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gu_piao.zui_di2
     *
     * @param zuiDi2 the value for gu_piao.zui_di2
     *
     * @mbggenerated
     */
    public void setZuiDi2(Double zuiDi2) {
        this.zuiDi2 = zuiDi2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gu_piao.zhen_fu
     *
     * @return the value of gu_piao.zhen_fu
     *
     * @mbggenerated
     */
    public Double getZhenFu() {
        return zhenFu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gu_piao.zhen_fu
     *
     * @param zhenFu the value for gu_piao.zhen_fu
     *
     * @mbggenerated
     */
    public void setZhenFu(Double zhenFu) {
        this.zhenFu = zhenFu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gu_piao.liu_tong_shi_zhi
     *
     * @return the value of gu_piao.liu_tong_shi_zhi
     *
     * @mbggenerated
     */
    public Double getLiuTongShiZhi() {
        return liuTongShiZhi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gu_piao.liu_tong_shi_zhi
     *
     * @param liuTongShiZhi the value for gu_piao.liu_tong_shi_zhi
     *
     * @mbggenerated
     */
    public void setLiuTongShiZhi(Double liuTongShiZhi) {
        this.liuTongShiZhi = liuTongShiZhi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gu_piao.zong_shi_zhi
     *
     * @return the value of gu_piao.zong_shi_zhi
     *
     * @mbggenerated
     */
    public Double getZongShiZhi() {
        return zongShiZhi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gu_piao.zong_shi_zhi
     *
     * @param zongShiZhi the value for gu_piao.zong_shi_zhi
     *
     * @mbggenerated
     */
    public void setZongShiZhi(Double zongShiZhi) {
        this.zongShiZhi = zongShiZhi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gu_piao.shi_jing_lu
     *
     * @return the value of gu_piao.shi_jing_lu
     *
     * @mbggenerated
     */
    public Double getShiJingLu() {
        return shiJingLu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gu_piao.shi_jing_lu
     *
     * @param shiJingLu the value for gu_piao.shi_jing_lu
     *
     * @mbggenerated
     */
    public void setShiJingLu(Double shiJingLu) {
        this.shiJingLu = shiJingLu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gu_piao.zhang_ting_jia
     *
     * @return the value of gu_piao.zhang_ting_jia
     *
     * @mbggenerated
     */
    public Double getZhangTingJia() {
        return zhangTingJia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gu_piao.zhang_ting_jia
     *
     * @param zhangTingJia the value for gu_piao.zhang_ting_jia
     *
     * @mbggenerated
     */
    public void setZhangTingJia(Double zhangTingJia) {
        this.zhangTingJia = zhangTingJia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gu_piao.die_ting_jia
     *
     * @return the value of gu_piao.die_ting_jia
     *
     * @mbggenerated
     */
    public Double getDieTingJia() {
        return dieTingJia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gu_piao.die_ting_jia
     *
     * @param dieTingJia the value for gu_piao.die_ting_jia
     *
     * @mbggenerated
     */
    public void setDieTingJia(Double dieTingJia) {
        this.dieTingJia = dieTingJia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gu_piao.create_time
     *
     * @return the value of gu_piao.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gu_piao.create_time
     *
     * @param createTime the value for gu_piao.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gu_piao.create_guid
     *
     * @return the value of gu_piao.create_guid
     *
     * @mbggenerated
     */
    public String getCreateGuid() {
        return createGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gu_piao.create_guid
     *
     * @param createGuid the value for gu_piao.create_guid
     *
     * @mbggenerated
     */
    public void setCreateGuid(String createGuid) {
        this.createGuid = createGuid == null ? null : createGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gu_piao.modify_time
     *
     * @return the value of gu_piao.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gu_piao.modify_time
     *
     * @param modifyTime the value for gu_piao.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gu_piao.modify_guid
     *
     * @return the value of gu_piao.modify_guid
     *
     * @mbggenerated
     */
    public String getModifyGuid() {
        return modifyGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gu_piao.modify_guid
     *
     * @param modifyGuid the value for gu_piao.modify_guid
     *
     * @mbggenerated
     */
    public void setModifyGuid(String modifyGuid) {
        this.modifyGuid = modifyGuid == null ? null : modifyGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gu_piao.is_deleted
     *
     * @return the value of gu_piao.is_deleted
     *
     * @mbggenerated
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gu_piao.is_deleted
     *
     * @param isDeleted the value for gu_piao.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gu_piao
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        GuPiao other = (GuPiao) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getMingZi() == null ? other.getMingZi() == null : this.getMingZi().equals(other.getMingZi()))
            && (this.getDaiMa() == null ? other.getDaiMa() == null : this.getDaiMa().equals(other.getDaiMa()))
            && (this.getDangQianJiaGe() == null ? other.getDangQianJiaGe() == null : this.getDangQianJiaGe().equals(other.getDangQianJiaGe()))
            && (this.getZuoShou() == null ? other.getZuoShou() == null : this.getZuoShou().equals(other.getZuoShou()))
            && (this.getJinKai() == null ? other.getJinKai() == null : this.getJinKai().equals(other.getJinKai()))
            && (this.getChengJiaoLiangShou() == null ? other.getChengJiaoLiangShou() == null : this.getChengJiaoLiangShou().equals(other.getChengJiaoLiangShou()))
            && (this.getWaiPan() == null ? other.getWaiPan() == null : this.getWaiPan().equals(other.getWaiPan()))
            && (this.getNeiPan() == null ? other.getNeiPan() == null : this.getNeiPan().equals(other.getNeiPan()))
            && (this.getMaiYi() == null ? other.getMaiYi() == null : this.getMaiYi().equals(other.getMaiYi()))
            && (this.getMaiYiLiangShou2() == null ? other.getMaiYiLiangShou2() == null : this.getMaiYiLiangShou2().equals(other.getMaiYiLiangShou2()))
            && (this.getMai2() == null ? other.getMai2() == null : this.getMai2().equals(other.getMai2()))
            && (this.getMai3() == null ? other.getMai3() == null : this.getMai3().equals(other.getMai3()))
            && (this.getMai4() == null ? other.getMai4() == null : this.getMai4().equals(other.getMai4()))
            && (this.getMai5() == null ? other.getMai5() == null : this.getMai5().equals(other.getMai5()))
            && (this.getMaYi() == null ? other.getMaYi() == null : this.getMaYi().equals(other.getMaYi()))
            && (this.getMaYiLiang() == null ? other.getMaYiLiang() == null : this.getMaYiLiang().equals(other.getMaYiLiang()))
            && (this.getMa2() == null ? other.getMa2() == null : this.getMa2().equals(other.getMa2()))
            && (this.getMa3() == null ? other.getMa3() == null : this.getMa3().equals(other.getMa3()))
            && (this.getMa4() == null ? other.getMa4() == null : this.getMa4().equals(other.getMa4()))
            && (this.getMa5() == null ? other.getMa5() == null : this.getMa5().equals(other.getMa5()))
            && (this.getZuiJinZhuBiChengJiao() == null ? other.getZuiJinZhuBiChengJiao() == null : this.getZuiJinZhuBiChengJiao().equals(other.getZuiJinZhuBiChengJiao()))
            && (this.getShiJian() == null ? other.getShiJian() == null : this.getShiJian().equals(other.getShiJian()))
            && (this.getZhangDie() == null ? other.getZhangDie() == null : this.getZhangDie().equals(other.getZhangDie()))
            && (this.getZhangDie2() == null ? other.getZhangDie2() == null : this.getZhangDie2().equals(other.getZhangDie2()))
            && (this.getZuiGao() == null ? other.getZuiGao() == null : this.getZuiGao().equals(other.getZuiGao()))
            && (this.getZuiDi() == null ? other.getZuiDi() == null : this.getZuiDi().equals(other.getZuiDi()))
            && (this.getJiaGe() == null ? other.getJiaGe() == null : this.getJiaGe().equals(other.getJiaGe()))
            && (this.getChengJiaoLiang() == null ? other.getChengJiaoLiang() == null : this.getChengJiaoLiang().equals(other.getChengJiaoLiang()))
            && (this.getChengJiaoE() == null ? other.getChengJiaoE() == null : this.getChengJiaoE().equals(other.getChengJiaoE()))
            && (this.getChengJiaoLiangShou2() == null ? other.getChengJiaoLiangShou2() == null : this.getChengJiaoLiangShou2().equals(other.getChengJiaoLiangShou2()))
            && (this.getChengJiaoEWan2() == null ? other.getChengJiaoEWan2() == null : this.getChengJiaoEWan2().equals(other.getChengJiaoEWan2()))
            && (this.getHuanShouLu() == null ? other.getHuanShouLu() == null : this.getHuanShouLu().equals(other.getHuanShouLu()))
            && (this.getShiYingLu() == null ? other.getShiYingLu() == null : this.getShiYingLu().equals(other.getShiYingLu()))
            && (this.getZuiGao2() == null ? other.getZuiGao2() == null : this.getZuiGao2().equals(other.getZuiGao2()))
            && (this.getZuiDi2() == null ? other.getZuiDi2() == null : this.getZuiDi2().equals(other.getZuiDi2()))
            && (this.getZhenFu() == null ? other.getZhenFu() == null : this.getZhenFu().equals(other.getZhenFu()))
            && (this.getLiuTongShiZhi() == null ? other.getLiuTongShiZhi() == null : this.getLiuTongShiZhi().equals(other.getLiuTongShiZhi()))
            && (this.getZongShiZhi() == null ? other.getZongShiZhi() == null : this.getZongShiZhi().equals(other.getZongShiZhi()))
            && (this.getShiJingLu() == null ? other.getShiJingLu() == null : this.getShiJingLu().equals(other.getShiJingLu()))
            && (this.getZhangTingJia() == null ? other.getZhangTingJia() == null : this.getZhangTingJia().equals(other.getZhangTingJia()))
            && (this.getDieTingJia() == null ? other.getDieTingJia() == null : this.getDieTingJia().equals(other.getDieTingJia()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateGuid() == null ? other.getCreateGuid() == null : this.getCreateGuid().equals(other.getCreateGuid()))
            && (this.getModifyTime() == null ? other.getModifyTime() == null : this.getModifyTime().equals(other.getModifyTime()))
            && (this.getModifyGuid() == null ? other.getModifyGuid() == null : this.getModifyGuid().equals(other.getModifyGuid()))
            && (this.getIsDeleted() == null ? other.getIsDeleted() == null : this.getIsDeleted().equals(other.getIsDeleted()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gu_piao
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getMingZi() == null) ? 0 : getMingZi().hashCode());
        result = prime * result + ((getDaiMa() == null) ? 0 : getDaiMa().hashCode());
        result = prime * result + ((getDangQianJiaGe() == null) ? 0 : getDangQianJiaGe().hashCode());
        result = prime * result + ((getZuoShou() == null) ? 0 : getZuoShou().hashCode());
        result = prime * result + ((getJinKai() == null) ? 0 : getJinKai().hashCode());
        result = prime * result + ((getChengJiaoLiangShou() == null) ? 0 : getChengJiaoLiangShou().hashCode());
        result = prime * result + ((getWaiPan() == null) ? 0 : getWaiPan().hashCode());
        result = prime * result + ((getNeiPan() == null) ? 0 : getNeiPan().hashCode());
        result = prime * result + ((getMaiYi() == null) ? 0 : getMaiYi().hashCode());
        result = prime * result + ((getMaiYiLiangShou2() == null) ? 0 : getMaiYiLiangShou2().hashCode());
        result = prime * result + ((getMai2() == null) ? 0 : getMai2().hashCode());
        result = prime * result + ((getMai3() == null) ? 0 : getMai3().hashCode());
        result = prime * result + ((getMai4() == null) ? 0 : getMai4().hashCode());
        result = prime * result + ((getMai5() == null) ? 0 : getMai5().hashCode());
        result = prime * result + ((getMaYi() == null) ? 0 : getMaYi().hashCode());
        result = prime * result + ((getMaYiLiang() == null) ? 0 : getMaYiLiang().hashCode());
        result = prime * result + ((getMa2() == null) ? 0 : getMa2().hashCode());
        result = prime * result + ((getMa3() == null) ? 0 : getMa3().hashCode());
        result = prime * result + ((getMa4() == null) ? 0 : getMa4().hashCode());
        result = prime * result + ((getMa5() == null) ? 0 : getMa5().hashCode());
        result = prime * result + ((getZuiJinZhuBiChengJiao() == null) ? 0 : getZuiJinZhuBiChengJiao().hashCode());
        result = prime * result + ((getShiJian() == null) ? 0 : getShiJian().hashCode());
        result = prime * result + ((getZhangDie() == null) ? 0 : getZhangDie().hashCode());
        result = prime * result + ((getZhangDie2() == null) ? 0 : getZhangDie2().hashCode());
        result = prime * result + ((getZuiGao() == null) ? 0 : getZuiGao().hashCode());
        result = prime * result + ((getZuiDi() == null) ? 0 : getZuiDi().hashCode());
        result = prime * result + ((getJiaGe() == null) ? 0 : getJiaGe().hashCode());
        result = prime * result + ((getChengJiaoLiang() == null) ? 0 : getChengJiaoLiang().hashCode());
        result = prime * result + ((getChengJiaoE() == null) ? 0 : getChengJiaoE().hashCode());
        result = prime * result + ((getChengJiaoLiangShou2() == null) ? 0 : getChengJiaoLiangShou2().hashCode());
        result = prime * result + ((getChengJiaoEWan2() == null) ? 0 : getChengJiaoEWan2().hashCode());
        result = prime * result + ((getHuanShouLu() == null) ? 0 : getHuanShouLu().hashCode());
        result = prime * result + ((getShiYingLu() == null) ? 0 : getShiYingLu().hashCode());
        result = prime * result + ((getZuiGao2() == null) ? 0 : getZuiGao2().hashCode());
        result = prime * result + ((getZuiDi2() == null) ? 0 : getZuiDi2().hashCode());
        result = prime * result + ((getZhenFu() == null) ? 0 : getZhenFu().hashCode());
        result = prime * result + ((getLiuTongShiZhi() == null) ? 0 : getLiuTongShiZhi().hashCode());
        result = prime * result + ((getZongShiZhi() == null) ? 0 : getZongShiZhi().hashCode());
        result = prime * result + ((getShiJingLu() == null) ? 0 : getShiJingLu().hashCode());
        result = prime * result + ((getZhangTingJia() == null) ? 0 : getZhangTingJia().hashCode());
        result = prime * result + ((getDieTingJia() == null) ? 0 : getDieTingJia().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateGuid() == null) ? 0 : getCreateGuid().hashCode());
        result = prime * result + ((getModifyTime() == null) ? 0 : getModifyTime().hashCode());
        result = prime * result + ((getModifyGuid() == null) ? 0 : getModifyGuid().hashCode());
        result = prime * result + ((getIsDeleted() == null) ? 0 : getIsDeleted().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gu_piao
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", mingZi=").append(mingZi);
        sb.append(", daiMa=").append(daiMa);
        sb.append(", dangQianJiaGe=").append(dangQianJiaGe);
        sb.append(", zuoShou=").append(zuoShou);
        sb.append(", jinKai=").append(jinKai);
        sb.append(", chengJiaoLiangShou=").append(chengJiaoLiangShou);
        sb.append(", waiPan=").append(waiPan);
        sb.append(", neiPan=").append(neiPan);
        sb.append(", maiYi=").append(maiYi);
        sb.append(", maiYiLiangShou2=").append(maiYiLiangShou2);
        sb.append(", mai2=").append(mai2);
        sb.append(", mai3=").append(mai3);
        sb.append(", mai4=").append(mai4);
        sb.append(", mai5=").append(mai5);
        sb.append(", maYi=").append(maYi);
        sb.append(", maYiLiang=").append(maYiLiang);
        sb.append(", ma2=").append(ma2);
        sb.append(", ma3=").append(ma3);
        sb.append(", ma4=").append(ma4);
        sb.append(", ma5=").append(ma5);
        sb.append(", zuiJinZhuBiChengJiao=").append(zuiJinZhuBiChengJiao);
        sb.append(", shiJian=").append(shiJian);
        sb.append(", zhangDie=").append(zhangDie);
        sb.append(", zhangDie2=").append(zhangDie2);
        sb.append(", zuiGao=").append(zuiGao);
        sb.append(", zuiDi=").append(zuiDi);
        sb.append(", jiaGe=").append(jiaGe);
        sb.append(", chengJiaoLiang=").append(chengJiaoLiang);
        sb.append(", chengJiaoE=").append(chengJiaoE);
        sb.append(", chengJiaoLiangShou2=").append(chengJiaoLiangShou2);
        sb.append(", chengJiaoEWan2=").append(chengJiaoEWan2);
        sb.append(", huanShouLu=").append(huanShouLu);
        sb.append(", shiYingLu=").append(shiYingLu);
        sb.append(", zuiGao2=").append(zuiGao2);
        sb.append(", zuiDi2=").append(zuiDi2);
        sb.append(", zhenFu=").append(zhenFu);
        sb.append(", liuTongShiZhi=").append(liuTongShiZhi);
        sb.append(", zongShiZhi=").append(zongShiZhi);
        sb.append(", shiJingLu=").append(shiJingLu);
        sb.append(", zhangTingJia=").append(zhangTingJia);
        sb.append(", dieTingJia=").append(dieTingJia);
        sb.append(", createTime=").append(createTime);
        sb.append(", createGuid=").append(createGuid);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", modifyGuid=").append(modifyGuid);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}