package com.pwz.sys.dao;


import com.pwz.back.dao.BaseDao;
import com.pwz.sys.pojo.SysAuth;

public interface SysAuthMapper  extends BaseDao<SysAuth, String> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_auth
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String authId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_auth
     *
     * @mbggenerated
     */
    int insert(SysAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_auth
     *
     * @mbggenerated
     */
    int insertSelective(SysAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_auth
     *
     * @mbggenerated
     */
    SysAuth selectByPrimaryKey(String authId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_auth
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_auth
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysAuth record);
}