package com.pwz.sys.dao;


import com.pwz.back.dao.BaseDao;
import com.pwz.sys.pojo.SysGroupAuth;

public interface SysGroupAuthMapper  extends BaseDao<SysGroupAuth, String> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_group_auth
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String groupAuthId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_group_auth
     *
     * @mbggenerated
     */
    int insert(SysGroupAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_group_auth
     *
     * @mbggenerated
     */
    int insertSelective(SysGroupAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_group_auth
     *
     * @mbggenerated
     */
    SysGroupAuth selectByPrimaryKey(String groupAuthId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_group_auth
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysGroupAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_group_auth
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysGroupAuth record);
}