package com.pwz.sys.dao;


import com.pwz.back.dao.BaseDao;
import com.pwz.sys.pojo.SysUserGroup;

public interface SysUserGroupMapper  extends BaseDao<SysUserGroup, String> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_group
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String userGroupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_group
     *
     * @mbggenerated
     */
    int insert(SysUserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_group
     *
     * @mbggenerated
     */
    int insertSelective(SysUserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_group
     *
     * @mbggenerated
     */
    SysUserGroup selectByPrimaryKey(String userGroupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysUserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysUserGroup record);
}