package com.pwz.gupiao.dao;


import com.pwz.back.dao.BaseDao;
import com.pwz.gupiao.pojo.GuPiao;

import java.util.HashMap;
import java.util.List;

public interface GuPiaoMapper extends BaseDao<GuPiao, String> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gu_piao
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gu_piao
     *
     * @mbggenerated
     */
    int insert(GuPiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gu_piao
     *
     * @mbggenerated
     */
    int insertSelective(GuPiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gu_piao
     *
     * @mbggenerated
     */
    GuPiao selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gu_piao
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GuPiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gu_piao
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GuPiao record);


    int count(HashMap<Object, Object> objectObjectHashMap);
    List<GuPiao> findAll();
}