package com.gupiao.dao;


import com.gupiao.pojo.GuPiao;

public interface GuPiaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gu_piao
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gu_piao
     *
     * @mbggenerated
     */
    int insert(GuPiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gu_piao
     *
     * @mbggenerated
     */
    int insertSelective(GuPiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gu_piao
     *
     * @mbggenerated
     */
    GuPiao selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gu_piao
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GuPiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gu_piao
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GuPiao record);
}